version: '3'

services:
  postgres:
    image: postgres:latest
    env_file:
      - .env.local
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

  node-app:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    env_file:
      - .env.local
    ports:
      - "8000:8000"
